[Settings]
ID = "8b97a0b5-abe5-4c73-a538-89a15287daf5"

# Settings in the [build] context are global and are applied to all contexts unless otherwise overridden by more specific contexts.  

[build]
  # This is the directory to change to before starting a build.
  base    = "lambda-resume-builder/"
  # NOTE: This is where we will look for package.json/.nvmrc/etc, not root.
  # This is the directory that you are publishing from (relative to root of your repo)
  publish = "lambda-resume-builder/build/"
  # This will be your default build command
  command = "yarn build"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200